-- DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING.
-- Standard Timers library used in almost all Dota 2 custom games.

if Timers == nil then
    print ( '[Timers] creating Timers' )
    Timers = {}
    Timers.__index = Timers
end

function Timers:CreateTimer(name, args)
    if type(name) == "function" then
        args = { callback = name }
        name = DoUniqueString("timer")
    elseif type(name) == "table" then
        args = name
        name = DoUniqueString("timer")
    end

    if not args.callback then
        print("Timer created without callback!")
        return
    end

    local now = GameRules:GetGameTime()

    if args.useGameTime ~= true then
        now = Time()
    end

    if args.endTime == nil then
        if args.useGameTime ~= true then
            args.endTime = Time() + args.delay
        else
            args.endTime = GameRules:GetGameTime() + args.delay
        end
    end

    self.timers = self.timers or {}
    self.timers[name] = args

    return name
end

function Timers:RemoveTimer(name)
    if self.timers then
        self.timers[name] = nil
    end
end

function Timers:Think()
    if not self.timers then return end

    local now = GameRules:GetGameTime()

    for k,v in pairs(self.timers) do
        local useGameTime = true
        if v.useGameTime == false then
            now = Time()
        end

        if now >= v.endTime then

            self.timers[k] = nil

            local status, nextCall = pcall(v.callback, GameRules:GetGameTime(), v)

            if status then
                if nextCall then
                    v.endTime = now + nextCall
                    self.timers[k] = v
                end
            else
                print("Timer Error: ", nextCall)
            end
        end
    end

    return 0.01
end

if not Timers.started then
    Timers.started = true
    Timers:CreateTimer(function()
        return Timers:Think()
    end)
end
